additonal time for imex startup and retry failed scontrol calls

diff --git a/tools/prologs-epilogs/imex_prolog b/tools/prologs-epilogs/imex_prolog
--- a/tools/prologs-epilogs/imex_prolog
+++ b/tools/prologs-epilogs/imex_prolog
@@ -21,6 +21,7 @@ fi
 
 activate_imex() {
   set -ex
+  set -o pipefail
 
   # Clean the config file in case the service gets started by accident
   > /etc/nvidia-imex/nodes_config.cfg
@@ -51,7 +52,18 @@ activate_imex() {
   fi
 
   # update peer list
-  scontrol -a show node "${SLURM_NODELIST}" -o | sed 's/^.* NodeAddr=\([^ ]*\).*/\1/' > /etc/nvidia-imex/nodes_config.cfg
+  for i in {1..3}; do
+    scontrol -a show node "${SLURM_NODELIST}" -o | sed 's/^.* NodeAddr=\([^ ]*\).*/\1/' > /etc/nvidia-imex/nodes_config.cfg && break
+
+    # Exit with error if this was the third and final failed attempt
+    if [[ $i -eq 3 ]]; then
+      echo "Error: scontrol failed on final attempt. Exiting prolog." >&2
+      exit 1
+    fi
+
+    echo "Warning: scontrol failed (attempt $i), retrying in 1s..." >&2
+    sleep 1
+  done
 
   # configure port and enable imex-ctl
   sed -i "s/SERVER_PORT.*/SERVER_PORT=${IMEX_SERVER_PORT}/" /etc/nvidia-imex/config.cfg
@@ -62,7 +74,7 @@ activate_imex() {
   systemctl start nvidia-imex
 
   # Actively poll to see if the service started successfully.
-  MAX_WAIT_SECONDS=20
+  MAX_WAIT_SECONDS=60
   for ((i=0; i<MAX_WAIT_SECONDS; i++)); do
     if systemctl is-active --quiet nvidia-imex; then
       break # Service is active, exit loop
@@ -71,8 +83,8 @@ activate_imex() {
   done
   if ((i == MAX_WAIT_SECONDS)); then
     echo "IMEX Prolog Error: nvidia-imex service did not start within ${MAX_WAIT_SECONDS}s." >&2
-    # Check the journal for errors
-    journalctl -u nvidia-imex --no-pager -n 20
+    # Check the journal for errors for all tries
+    journalctl -u nvidia-imex --no-pager -n ${MAX_WAIT_SECONDS}
     exit 1
   fi
 }
